.TH "ARSENAL" "3" "<date>" "<version>" "The Arsenal library documentation"
.SH NAME
Arsenal presentation \- The Arsenal library v<version>
.sp
Arsenal is a C library to integrate into a project, providing a solution to recurrent tasks.
.sp
.ce
----
.ce 0
.sp
.SH LIBRARY USAGE NOTES
.nr PI 2n
.IP \[bu] 2
It is recomended to make use of \fBerrno\fP to get more details about an error that occured, if needed.
.IP \[bu] 2
Every buffer memory and size used with the library should be properly defined and allocated before using them, otherwise some malfunctions can occur : A general rule is that never the functions of Arsenal will allocate memory in a buffer that needs further \fBfree(1)\fP call.
.sp
Function\-specific security notices will be described further in the relevant sections.
.SH FUNCTIONALITIES REFERENCES
.SS \fBUser input\fP
See \fBarsenal-user-input(3)\fP for full content.
.SS \fBStylized display\fP
See \fBarsenal-display(3)\fP for full content.
.SS \fBString manipulation\fP
See \fBarsenal-string(3)\fP for full content.
.SS \fBNetworking\fP
See \fBarsenal-networking(3)\fP for full content.
.SS \fBRandom string\fP
See \fBarsenal-random(3)\fP for full content.
.SS \fBFile manipulation\fP
See \fBarsenal-file(3)\fP for full content.